[build]
  command = "npm run build"
  publish = ".next"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  framework = "next"

[[plugins]]
  package = "@netlify/next"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"